<?php
session_start();

function require_admin_login(): void {
    if (!isset($_SESSION['user_id']) || ($_SESSION['role'] ?? '') !== 'admin') {
        header('Location: ../login/login.html');
        exit();
    }
}
require_admin_login();

include '../login/db_connect.php';

$success = null; $error = null;

$allTables = ['users','books','borrowings','attendance'];

function escape_sql(mysqli $conn, $val) {
    if ($val === null) return 'NULL';
    return "'".$conn->real_escape_string($val)."'";
}

function table_exists(mysqli $conn, string $table): bool {
    $sql = "SELECT COUNT(*) c FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ?";
    $stmt = $conn->prepare($sql);
    if (!$stmt) return false;
    $stmt->bind_param('s', $table);
    $stmt->execute();
    $res = $stmt->get_result();
    $row = $res ? $res->fetch_assoc() : ['c'=>0];
    return (int)($row['c'] ?? 0) > 0;
}

function dump_table_sql(mysqli $conn, string $table): string {
    if (!table_exists($conn, $table)) return "-- Skipping $table (does not exist)\n";
    $sql = "-- Dumping data for table `$table`\n";
    $res = $conn->query("SELECT * FROM `$table`");
    if (!$res) return $sql."-- Error selecting from $table: ".$conn->error."\n";
    while ($row = $res->fetch_assoc()) {
        $cols = array_map(function($c){ return "`".$c."`"; }, array_keys($row));
        $vals = array_map(function($v) use ($conn) { return escape_sql($conn, $v); }, array_values($row));
        $sql .= "INSERT INTO `$table` (".implode(',', $cols).") VALUES (".implode(',', $vals).");\n";
    }
    $sql .= "\n";
    return $sql;
}

function build_backup_sql(mysqli $conn, array $tables): string {
    $header = "-- Simple SQL backup generated by backup-restore.php\n".
              "SET FOREIGN_KEY_CHECKS=0;\n\n";
    $body = '';
    foreach ($tables as $t) {
        $t = preg_replace('/[^a-zA-Z0-9_]/','',$t);
        $body .= dump_table_sql($conn, $t);
    }
    $footer = "SET FOREIGN_KEY_CHECKS=1;\n";
    return $header.$body.$footer;
}

function run_sql_file(mysqli $conn, string $sql): array {
    $ok = 0; $fail = 0; $errors = [];
    // Split on semicolon followed by newline (matches our generated dumps); skip comments
    $stmts = preg_split("/;\s*\r?\n/", $sql);
    foreach ($stmts as $stmt) {
        $stmt = trim($stmt);
        if ($stmt === '' || strpos($stmt, '--') === 0 || strpos($stmt, '/*') === 0) continue;
        try {
            if ($conn->query($stmt) === true) { $ok++; }
            else { $fail++; $errors[] = $conn->error; }
        } catch (Throwable $e) {
            $fail++; $errors[] = $e->getMessage();
        }
    }
    return [$ok, $fail, $errors];
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $action = $_POST['action'] ?? '';

    if ($action === 'backup') {
        $tables = isset($_POST['tables']) && is_array($_POST['tables']) ? array_values(array_intersect($_POST['tables'], $allTables)) : $allTables;
        if (empty($tables)) $tables = $allTables;
        $sql = build_backup_sql($conn, $tables);
        $filename = 'backup_'.date('Ymd_His').'.sql';
        header('Content-Type: application/sql');
        header('Content-Disposition: attachment; filename="'.$filename.'"');
        header('Content-Length: '.strlen($sql));
        echo $sql;
        exit;
    } elseif ($action === 'restore') {
        if (!isset($_FILES['sql_file']) || $_FILES['sql_file']['error'] !== UPLOAD_ERR_OK) {
            $error = 'Upload failed or no file selected.';
        } else {
            $tmp = $_FILES['sql_file']['tmp_name'];
            $content = file_get_contents($tmp);
            if ($content === false) {
                $error = 'Unable to read uploaded file.';
            } else {
                [$ok, $fail, $errors] = run_sql_file($conn, $content);
                if ($fail === 0) $success = "Restore completed: $ok statements executed."; else $error = "Restore completed with $fail errors.";
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <title>Backup & Restore</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet" />
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography"></script>
    <script>
      tailwind.config = { darkMode: 'class', theme: { extend: { colors: { primary: '#31694E' }, fontFamily: { display: ['Poppins','sans-serif'] }, borderRadius: { DEFAULT: '0.5rem' } } } };
    </script>
  </head>
  <body class="font-display bg-background-light dark:bg-background-dark text-slate-700 dark:text-slate-300">
    <main class="flex h-screen">
      <aside class="w-64 hidden md:block bg-slate-50 dark:bg-slate-800 border-r border-slate-200 dark:border-slate-700">
        <div class="h-16 flex items-center px-6 border-b border-slate-200 dark:border-slate-700">
          <span class="material-icons text-primary mr-2">school</span>
          <span class="font-bold text-lg">Library System</span>
        </div>
        <nav class="p-4 space-y-2">
          <a class="block px-4 py-2 text-sm font-medium text-slate-600 dark:text-slate-300 hover:bg-primary hover:text-white rounded-md" href="admin.php"><span class="material-icons align-middle mr-2">dashboard</span> Dashboard</a>
          <a class="block px-4 py-2 text-sm font-medium text-slate-600 dark:text-slate-300 hover:bg-primary hover:text-white rounded-md" href="book-management.php"><span class="material-icons align-middle mr-2">menu_book</span> Book Management</a>
          <a class="block px-4 py-2 text-sm font-medium text-slate-600 dark:text-slate-300 hover:bg-primary hover:text-white rounded-md" href="user-management.php"><span class="material-icons align-middle mr-2">group</span> User Management</a>
          <a class="block px-4 py-2 text-sm font-medium" href="borrow.php"><span class="material-icons align-middle mr-2">history</span> Borrowing History</a>
          <a class="block px-4 py-2 text-sm font-medium" href="Overdue-alerts.php"><span class="material-icons align-middle mr-2">warning</span> Overdue Alerts</a>
          <a class="flex items-center px-4 py-2 text-sm font-medium text-slate-600 dark:text-slate-300 hover:bg-primary hover:text-white rounded-md transform transition-all duration-150 hover:translate-x-1 hover:shadow-md" href="Global-logs.php">
            <span class="material-icons mr-3">analytics</span>
            Global Logs
          </a>
          <a class="block px-4 py-2 text-sm font-medium bg-primary text-white rounded-md" href="backup-restore.php"><span class="material-icons align-middle mr-2">backup</span> Backup & Restore</a>
           <a class="flex items-center px-4 py-2 text-sm font-medium text-slate-600 dark:text-slate-300 hover:bg-primary hover:text-white rounded-md transform transition-all duration-150 hover:translate-x-1 hover:shadow-md"
                    href="Attendance-logs.php">
                    <span class="material-icons mr-3">event_available</span>
                    Attendance Logs
                </a>
          <a class="flex items-center px-4 py-2 text-sm font-medium text-slate-600 dark:text-slate-300 hover:bg-primary hover:text-white rounded-md transform transition-all duration-150 hover:translate-x-1 hover:shadow-md" href="change-password.php">
            <span class="material-icons mr-3">lock</span>
            Change Password
          </a>
        </nav>
      </aside>
      <div class="flex-1 flex flex-col">
        <header class="h-16 flex items-center justify-between px-8 bg-slate-50 dark:bg-slate-800 border-b border-slate-200 dark:border-slate-700">
          <h1 class="text-xl font-semibold">Admin Dashboard</h1>
          <div class="text-right">
            <div class="font-medium text-sm"><?php echo htmlspecialchars($_SESSION['username'] ?? ''); ?></div>
            <div class="text-xs text-slate-500"><?php echo htmlspecialchars($_SESSION['email'] ?? ''); ?></div>
          </div>
        </header>
        <div class="flex-1 p-8 overflow-y-auto">
          <div class="bg-white dark:bg-gray-900 rounded-lg p-6">
            <div class="flex items-center justify-between mb-6">
              <div>
                <h2 class="text-2xl font-bold text-gray-900 dark:text-white">Backup & Restore</h2>
                <p class="text-gray-500 dark:text-gray-400">Create backups and restore data for key tables.</p>
              </div>
            </div>

            <?php if ($success): ?>
              <div class="mb-6 p-3 border border-green-300 bg-green-50 text-green-800 rounded"><?php echo htmlspecialchars($success); ?></div>
            <?php endif; ?>
            <?php if ($error): ?>
              <div class="mb-6 p-3 border border-red-300 bg-red-50 text-red-800 rounded"><?php echo htmlspecialchars($error); ?></div>
            <?php endif; ?>

            <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <section class="p-4 border border-gray-200 dark:border-gray-700 rounded-lg">
                <h3 class="text-center text-lg font-semibold mb-3">Create SQL Backup</h3>
                <form method="POST" class="space-y-4">
                  <input type="hidden" name="action" value="backup" />
                  <p class="text-sm text-slate-500">Select tables to include:</p>
                  <div class="grid grid-cols-2 gap-2">
                    <?php foreach ($allTables as $t): ?>
                      <label class="flex items-center gap-2 text-sm">
                        <input type="checkbox" name="tables[]" value="<?php echo $t; ?>" class="h-4 w-4" checked />
                        <span class="capitalize"><?php echo $t; ?></span>
                      </label>
                    <?php endforeach; ?>
                  </div>
                  <button class="px-4 py-2 bg-primary text-white rounded">Download .sql</button>
                </form>
              </section>

              <section class="p-4 border border-gray-200 dark:border-gray-700 rounded-lg">
                <h3 class="text-center text-lg font-semibold mb-3">Restore From SQL</h3>
                <form method="POST" enctype="multipart/form-data" class="space-y-4">
                  <input type="hidden" name="action" value="restore" />
                  <div>
                    <label class="block text-sm font-medium mb-1">Upload .sql file</label>
                    <input type="file" name="sql_file" accept=".sql" class="block w-full text-sm" required />
                  </div>
                  <p class="text-xs text-slate-500">Note: This runner executes statements in the file sequentially. Large or complex schema dumps may require mysqldump-based restore.</p>
                  <button class="px-4 py-2 border rounded hover:bg-gray-50">Run Restore</button>
                </form>
              </section>
            </div>

          </div>
        </div>
        <footer class="h-14 flex items-center justify-between px-8 bg-slate-50 dark:bg-slate-800 border-t border-slate-200 dark:border-slate-700">
          <div class="text-sm">© 2025 OMSC Library</div>
          <div class="text-sm text-slate-500 space-x-4">
            <a href="/privacy.html" class="hover:text-primary">Privacy</a>
            <a href="/terms.html" class="hover:text-primary">Terms</a>
          </div>
        </footer>
      </div>
    </main>
  </body>
</html>
